# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 03:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='statue',
            field=models.IntegerField(default=0, verbose_name=16),
            preserve_default=False,
        ),
    ]
